# Generated by Django 5.2.1 on 2025-05-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tags',
            new_name='tag',
        ),
    ]
