# Generated by Django 5.2.1 on 2025-06-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_about_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/sbcf-default-avatar.png', null=True, upload_to='img/'),
        ),
    ]
